/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LocalStore {
    }
}
declare global {
    interface HTMLLocalStoreElement extends Components.LocalStore, HTMLStencilElement {
    }
    var HTMLLocalStoreElement: {
        prototype: HTMLLocalStoreElement;
        new (): HTMLLocalStoreElement;
    };
    interface HTMLElementTagNameMap {
        "local-store": HTMLLocalStoreElement;
    }
}
declare namespace LocalJSX {
    interface LocalStore {
    }
    interface IntrinsicElements {
        "local-store": LocalStore;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "local-store": LocalJSX.LocalStore & JSXBase.HTMLAttributes<HTMLLocalStoreElement>;
        }
    }
}
